#!/bin/bash
# based on
# https://github.com/sjswuitchik/duck_comp_gen/blob/master/03a_cnee_analysis/06_PhyloAcc/

# in /n/holylfs/LABS/informatics/nectar_genomes/analyses/CNEEanalysis/03_phyloacc/

# mkdir -p input
# put named.mod, fasta, cnee bed here
# in gwdg
# scp -rp galGal6_final_merged_CNEEs_named_fixchr2.bed mcko@login.rc.fas.harvard.edu:/n/holylfs/LABS/informatics/nectar_genomes/analyses/CNEEanalysis/03_phyloacc/input # worked
# awk 'BEGIN {OFS="\t"} {print $4, $2, $3}' galGal6_final_merged_CNEEs_named_fixchr2.bed > final_merged_CNEEs_named.bed

# will run batches of 200 elements each

# set up batch files
mkdir -p top1_batches
# get number of elements
num=$(wc -l input/final_merged_CNEEs_named.bed | cut -d ' ' -f 1)
# shuffle lines in random order with 0-n-1 from wc -l above
shuf -i 0-$num > top1_batches/full_list

# make input files
split -d -a 4 -l 200 top1_batches/full_list top1_batches/batch

# set up parameter and output files
mkdir -p top1_param
mkdir -p top1_outs

for I in $(seq 0 1877); # number of batches generated by line 22
do
  printf -v BATCH "%04d" $I
  PARTFILE=top1_batches/batch$BATCH
  PREFIX=batch${BATCH}
  cat > top1_param/run$I <<EOF
PHYTREE_FILE /n/holylfs/LABS/informatics/nectar_genomes/analyses/CNEEanalysis/03_phyloacc/input/nonconserved_4d_named.mod
SEG_FILE /n/holylfs/LABS/informatics/nectar_genomes/analyses/CNEEanalysis/03_phyloacc/input/final_merged_CNEEs_named.bed
ALIGN_FILE /n/holylfs/LABS/informatics/nectar_genomes/analyses/CNEEanalysis/03_phyloacc/input/multi.anno.fasta
RESULT_FOLDER top1_outs
PREFIX $PREFIX
ID_FILE $PARTFILE
CHAIN 1
BURNIN 1000
MCMC 4000
CONSERVE_PRIOR_A 5
CONSERVE_PRIOR_B 0.04
ACCE_PRIOR_A 10
ACCE_PRIOR_B 0.2
HYPER_GRATE_A 3
HYPER_GRATE_B 1
TARGETSPECIES HLphyNov1;HLacaPus1;HLcalAnn5;HLfloFus1
CONSERVE HLparMaj1;pseHum1;HLzosLat1;HLtaeGut4;HLserCan1;ficAlb2;HLcorCor3;HLlicCas1;HLmalCya1;HLfurRuf1;HLempTra1;melUnd1;HLtriMol2;HLstrHab1;falPer1;falChe1;HLfalTin1;HLtytAlb2;halLeu1;aptFor1;HLcalPug1;opiHoa1;HLchaPel1;cucCan1;HLcolLiv2;galGal6
GAPCHAR -
NUM_THREAD 8
VERBOSE 0
CONSTOMIS 0.01
GAP_PROP 0.8
TRIM_GAP_PERCENT 0.8
EOF
done
